#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("p2p_project.Resource", IsApplication=true)]

namespace p2p_project
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUpStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_file = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ProgressBarStyle = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070011
			public const int btnCancelSearch = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int btnP2pSearch = 2131165200;
			
			// aapt resource value: 0x7f070005
			public const int btnSend = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int btnSendFile = 2131165188;
			
			// aapt resource value: 0x7f070013
			public const int btnSendFileGallery = 2131165203;
			
			// aapt resource value: 0x7f07000f
			public const int btnSendFileHome = 2131165199;
			
			// aapt resource value: 0x7f070014
			public const int btnSendFileNow = 2131165204;
			
			// aapt resource value: 0x7f07000d
			public const int btnSendMessageHome = 2131165197;
			
			// aapt resource value: 0x7f070018
			public const int btnSignIn = 2131165208;
			
			// aapt resource value: 0x7f07000a
			public const int btnSignUp = 2131165194;
			
			// aapt resource value: 0x7f070015
			public const int imageViewSendFile = 2131165205;
			
			// aapt resource value: 0x7f070003
			public const int llContainer = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int lstMessages = 2131165186;
			
			// aapt resource value: 0x7f070012
			public const int lstPeers = 2131165202;
			
			// aapt resource value: 0x7f070000
			public const int txtAdapter = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int txtChat = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int txtConfermaPassword = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int txtGoToSignIn = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int txtNickname = 2131165191;
			
			// aapt resource value: 0x7f070016
			public const int txtNicknameSignIn = 2131165206;
			
			// aapt resource value: 0x7f07000e
			public const int txtORHome = 2131165198;
			
			// aapt resource value: 0x7f070001
			public const int txtOrario = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int txtPassword = 2131165192;
			
			// aapt resource value: 0x7f070017
			public const int txtPasswordSignIn = 2131165207;
			
			// aapt resource value: 0x7f07000c
			public const int txtSelectActivity = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Chat_template_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChatLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Data_template_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_sign_up = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HomeLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SelectFileLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SendFileLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SignInLayout = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
